### ISSUE TITLE
Add option to Expand/Collapse All Items in Multi-Item Edit Cloud App

### ISSUE THREAD

**Issue by kfeeken** [ExLibrisGroup/Cloud-app-items-po-line#2]
We have several users at our institution that are utilizing the Multiple Item Edit cloud app. However, some users are asking for an enhancement to the app. Most of the time, when using the App, they are editing all items on a given page. In the App, you have to expand each item individually, before you can make the necessary edits. Would it be possible to enhance the App, to include an Expand/Collapse All feature that would allow the user to Expand All Items for editing, instead of having to do it for each individual item?

**Comment by ori229** [comment]
Added a new button - https://github.com/ExLibrisGroup/Cloud-app-items-po-line/commit/0bb76344a35fd291c71f039a613e48e2213bc21d
